### ISSUE TITLE
Feat.req. Make app able to recover if possible all corrupted jpg files not only WA

### ISSUE THREAD

**Issue by necros2k7** [cdefgah/whatsapp-jpeg-repair#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Integrate other methods to fix jpgs automatically upon input file

**Describe alternatives you've considered**
Jpegmedic viewer methods would be great

**Additional context**

**Comment by cdefgah** [comment]
Hello, there.

Thank you for your feature request, I appreciate it. 

This tool is not intended to decrypt files, encrypted by ransomware. Only files broken by WhatsApp and it does not encrypt files, it just breaks JPEG file header.

Such tasks are very interesting, although they relate to the creation of a completely new product. Unfortunately, I do not have enough time to analyze files from different ransomware encryptors and study the methods of their encryption and decryption.

In case you want to process many image files at once, to fix contrast, brightness, orientation or other issues, not related to ransomware encryptors, I would recommend to use [ImageMagick](https://imagemagick.org/)

In case you have requests, directly related to my tool, feel free to contact me.

Here are sample feature requests that were related to my tool and that were accepted and implemented: 

[Request to create option to clean-up the source whatsapp files](https://github.com/cdefgah/whatsapp-jpeg-repair/issues/1)

[Add how to use section to readme](https://github.com/cdefgah/whatsapp-jpeg-repair/issues/4)

**Comment by necros2k7** [comment]
I meant corrupted jpegs with header damage or file structure itself not encrypted as such samples:
![DEMO-C1](https://user-images.githubusercontent.com/16452453/179498095-2d8e13c0-98b7-4eb6-9acd-4c28c90bf1d0.JPG)
![T2B](https://user-images.githubusercontent.com/16452453/179498105-ce9bf00b-e876-4927-a97c-988f05feaa7c.JPG)
