### ISSUE TITLE
Processing of a file list

### ISSUE THREAD

**Issue by B-G-T** [cdefgah/whatsapp-jpeg-repair#7]
I am using the program in combination with Lightroom 5.
It works really good but the directory-based approach is a bit cumbersome for this purpose (and maybe also in some other cases).

The possibility to commit a list of files (instead of paths) for processing would be a huge improvement, as this would allow calling it directly from within LR:
`WhatsAppJpegRepair.exe file1 file2 ...`

**Comment by B-G-T** [comment]
Lightroom passes the complete filenames incl. paths of the selected images as arguments when it calls external editors.
Example for a call:
`WhatsAppJpegRepair.exe "C:\Lightroom\Import1\imageA.jpg" "C:\Lightroom\Import2\imageB.jpg"`

WhatsAppJpegRepair should then fix these files at the original location and terminate.

This will simplify the fixing of broken WhatsApp images in Lightroom (and probably also other tools) tremendously.
If my understanding is right, it will also enable fixing by drag and drop in Windows.

**Comment by cdefgah** [comment]
Thank you for clarification.

I will include this functionality to the next version of the WhatsAppRepair.

As new version is released I will post information here and close this issue. 

Until that this issue will remain open.

Thank you for your insights.

**Comment by B-G-T** [comment]
Thanks a lot. I am looking forward to the new update!

**Comment by cdefgah** [comment]
I plan to implement and release new version on upcoming weekend. Hope nothing will interfere with my plans.

**Comment by cdefgah** [comment]
New version (2.2.0) released.

Please download version, suitable to your operating system here (expand `Assets` section): https://github.com/cdefgah/whatsapp-jpeg-repair/releases/tag/v2.2.0

And let me know, how does it work in your case. I've tested it, and it should work ok.
